export const GET_IMAGES_START = 'GET_IMAGES_START'
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR'
export const ON_CARD_LIKE_TOGGLE = 'ON_CARD_LIKE_TOGGLE'