export const SAVE_CREDENTIALS_START = 'SAVE_CREDENTIALS_START'
export const SAVE_CREDENTIALS_SUCCESS = 'SAVE_CREDENTIALS_SUCCESS'
export const SAVE_CREDENTIALS_FAIL = 'SAVE_CREDENTIALS_FAIL'

export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START'
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS'
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL'